//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discussion.srv {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Participant", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Participant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PseudoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Pseudo {
            get {
                return this.PseudoField;
            }
            set {
                if ((object.ReferenceEquals(this.PseudoField, value) != true)) {
                    this.PseudoField = value;
                    this.RaisePropertyChanged("Pseudo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatMessage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ChatMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PseudoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Pseudo {
            get {
                return this.PseudoField;
            }
            set {
                if ((object.ReferenceEquals(this.PseudoField, value) != true)) {
                    this.PseudoField = value;
                    this.RaisePropertyChanged("Pseudo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srv.ws_chatSoap")]
    public interface ws_chatSoap {
        
        // CODEGEN: Generating message contract since element name pseudo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Participer", ReplyAction="*")]
        Discussion.srv.ParticiperResponse Participer(Discussion.srv.ParticiperRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Participer", ReplyAction="*")]
        System.IAsyncResult BeginParticiper(Discussion.srv.ParticiperRequest request, System.AsyncCallback callback, object asyncState);
        
        Discussion.srv.ParticiperResponse EndParticiper(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name pseudo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Quiter", ReplyAction="*")]
        Discussion.srv.QuiterResponse Quiter(Discussion.srv.QuiterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Quiter", ReplyAction="*")]
        System.IAsyncResult BeginQuiter(Discussion.srv.QuiterRequest request, System.AsyncCallback callback, object asyncState);
        
        Discussion.srv.QuiterResponse EndQuiter(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClearAll", ReplyAction="*")]
        void ClearAll();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ClearAll", ReplyAction="*")]
        System.IAsyncResult BeginClearAll(System.AsyncCallback callback, object asyncState);
        
        void EndClearAll(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name text from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessage", ReplyAction="*")]
        Discussion.srv.SendMessageResponse SendMessage(Discussion.srv.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SendMessage", ReplyAction="*")]
        System.IAsyncResult BeginSendMessage(Discussion.srv.SendMessageRequest request, System.AsyncCallback callback, object asyncState);
        
        Discussion.srv.SendMessageResponse EndSendMessage(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name AllMessagesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllMessages", ReplyAction="*")]
        Discussion.srv.AllMessagesResponse AllMessages(Discussion.srv.AllMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AllMessages", ReplyAction="*")]
        System.IAsyncResult BeginAllMessages(Discussion.srv.AllMessagesRequest request, System.AsyncCallback callback, object asyncState);
        
        Discussion.srv.AllMessagesResponse EndAllMessages(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParticiperRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Participer", Namespace="http://tempuri.org/", Order=0)]
        public Discussion.srv.ParticiperRequestBody Body;
        
        public ParticiperRequest() {
        }
        
        public ParticiperRequest(Discussion.srv.ParticiperRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ParticiperRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pseudo;
        
        public ParticiperRequestBody() {
        }
        
        public ParticiperRequestBody(string pseudo) {
            this.pseudo = pseudo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParticiperResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ParticiperResponse", Namespace="http://tempuri.org/", Order=0)]
        public Discussion.srv.ParticiperResponseBody Body;
        
        public ParticiperResponse() {
        }
        
        public ParticiperResponse(Discussion.srv.ParticiperResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ParticiperResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Discussion.srv.Participant[] ParticiperResult;
        
        public ParticiperResponseBody() {
        }
        
        public ParticiperResponseBody(Discussion.srv.Participant[] ParticiperResult) {
            this.ParticiperResult = ParticiperResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuiterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Quiter", Namespace="http://tempuri.org/", Order=0)]
        public Discussion.srv.QuiterRequestBody Body;
        
        public QuiterRequest() {
        }
        
        public QuiterRequest(Discussion.srv.QuiterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class QuiterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pseudo;
        
        public QuiterRequestBody() {
        }
        
        public QuiterRequestBody(string pseudo) {
            this.pseudo = pseudo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuiterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QuiterResponse", Namespace="http://tempuri.org/", Order=0)]
        public Discussion.srv.QuiterResponseBody Body;
        
        public QuiterResponse() {
        }
        
        public QuiterResponse(Discussion.srv.QuiterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class QuiterResponseBody {
        
        public QuiterResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://tempuri.org/", Order=0)]
        public Discussion.srv.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(Discussion.srv.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pseudo;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(string text, string pseudo) {
            this.text = text;
            this.pseudo = pseudo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Discussion.srv.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(Discussion.srv.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Discussion.srv.ChatMessage[] SendMessageResult;
        
        public SendMessageResponseBody() {
        }
        
        public SendMessageResponseBody(Discussion.srv.ChatMessage[] SendMessageResult) {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllMessages", Namespace="http://tempuri.org/", Order=0)]
        public Discussion.srv.AllMessagesRequestBody Body;
        
        public AllMessagesRequest() {
        }
        
        public AllMessagesRequest(Discussion.srv.AllMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllMessagesRequestBody {
        
        public AllMessagesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllMessagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Discussion.srv.AllMessagesResponseBody Body;
        
        public AllMessagesResponse() {
        }
        
        public AllMessagesResponse(Discussion.srv.AllMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Discussion.srv.ChatMessage[] AllMessagesResult;
        
        public AllMessagesResponseBody() {
        }
        
        public AllMessagesResponseBody(Discussion.srv.ChatMessage[] AllMessagesResult) {
            this.AllMessagesResult = AllMessagesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ws_chatSoapChannel : Discussion.srv.ws_chatSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParticiperCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ParticiperCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Discussion.srv.Participant[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Discussion.srv.Participant[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SendMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Discussion.srv.ChatMessage[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Discussion.srv.ChatMessage[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AllMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AllMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Discussion.srv.ChatMessage[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Discussion.srv.ChatMessage[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ws_chatSoapClient : System.ServiceModel.ClientBase<Discussion.srv.ws_chatSoap>, Discussion.srv.ws_chatSoap {
        
        private BeginOperationDelegate onBeginParticiperDelegate;
        
        private EndOperationDelegate onEndParticiperDelegate;
        
        private System.Threading.SendOrPostCallback onParticiperCompletedDelegate;
        
        private BeginOperationDelegate onBeginQuiterDelegate;
        
        private EndOperationDelegate onEndQuiterDelegate;
        
        private System.Threading.SendOrPostCallback onQuiterCompletedDelegate;
        
        private BeginOperationDelegate onBeginClearAllDelegate;
        
        private EndOperationDelegate onEndClearAllDelegate;
        
        private System.Threading.SendOrPostCallback onClearAllCompletedDelegate;
        
        private BeginOperationDelegate onBeginSendMessageDelegate;
        
        private EndOperationDelegate onEndSendMessageDelegate;
        
        private System.Threading.SendOrPostCallback onSendMessageCompletedDelegate;
        
        private BeginOperationDelegate onBeginAllMessagesDelegate;
        
        private EndOperationDelegate onEndAllMessagesDelegate;
        
        private System.Threading.SendOrPostCallback onAllMessagesCompletedDelegate;
        
        public ws_chatSoapClient() {
        }
        
        public ws_chatSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ws_chatSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ws_chatSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ws_chatSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ParticiperCompletedEventArgs> ParticiperCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> QuiterCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ClearAllCompleted;
        
        public event System.EventHandler<SendMessageCompletedEventArgs> SendMessageCompleted;
        
        public event System.EventHandler<AllMessagesCompletedEventArgs> AllMessagesCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion.srv.ParticiperResponse Discussion.srv.ws_chatSoap.Participer(Discussion.srv.ParticiperRequest request) {
            return base.Channel.Participer(request);
        }
        
        public Discussion.srv.Participant[] Participer(string pseudo) {
            Discussion.srv.ParticiperRequest inValue = new Discussion.srv.ParticiperRequest();
            inValue.Body = new Discussion.srv.ParticiperRequestBody();
            inValue.Body.pseudo = pseudo;
            Discussion.srv.ParticiperResponse retVal = ((Discussion.srv.ws_chatSoap)(this)).Participer(inValue);
            return retVal.Body.ParticiperResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Discussion.srv.ws_chatSoap.BeginParticiper(Discussion.srv.ParticiperRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginParticiper(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginParticiper(string pseudo, System.AsyncCallback callback, object asyncState) {
            Discussion.srv.ParticiperRequest inValue = new Discussion.srv.ParticiperRequest();
            inValue.Body = new Discussion.srv.ParticiperRequestBody();
            inValue.Body.pseudo = pseudo;
            return ((Discussion.srv.ws_chatSoap)(this)).BeginParticiper(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion.srv.ParticiperResponse Discussion.srv.ws_chatSoap.EndParticiper(System.IAsyncResult result) {
            return base.Channel.EndParticiper(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Discussion.srv.Participant[] EndParticiper(System.IAsyncResult result) {
            Discussion.srv.ParticiperResponse retVal = ((Discussion.srv.ws_chatSoap)(this)).EndParticiper(result);
            return retVal.Body.ParticiperResult;
        }
        
        private System.IAsyncResult OnBeginParticiper(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string pseudo = ((string)(inValues[0]));
            return this.BeginParticiper(pseudo, callback, asyncState);
        }
        
        private object[] OnEndParticiper(System.IAsyncResult result) {
            Discussion.srv.Participant[] retVal = this.EndParticiper(result);
            return new object[] {
                    retVal};
        }
        
        private void OnParticiperCompleted(object state) {
            if ((this.ParticiperCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ParticiperCompleted(this, new ParticiperCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ParticiperAsync(string pseudo) {
            this.ParticiperAsync(pseudo, null);
        }
        
        public void ParticiperAsync(string pseudo, object userState) {
            if ((this.onBeginParticiperDelegate == null)) {
                this.onBeginParticiperDelegate = new BeginOperationDelegate(this.OnBeginParticiper);
            }
            if ((this.onEndParticiperDelegate == null)) {
                this.onEndParticiperDelegate = new EndOperationDelegate(this.OnEndParticiper);
            }
            if ((this.onParticiperCompletedDelegate == null)) {
                this.onParticiperCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnParticiperCompleted);
            }
            base.InvokeAsync(this.onBeginParticiperDelegate, new object[] {
                        pseudo}, this.onEndParticiperDelegate, this.onParticiperCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion.srv.QuiterResponse Discussion.srv.ws_chatSoap.Quiter(Discussion.srv.QuiterRequest request) {
            return base.Channel.Quiter(request);
        }
        
        public void Quiter(string pseudo) {
            Discussion.srv.QuiterRequest inValue = new Discussion.srv.QuiterRequest();
            inValue.Body = new Discussion.srv.QuiterRequestBody();
            inValue.Body.pseudo = pseudo;
            Discussion.srv.QuiterResponse retVal = ((Discussion.srv.ws_chatSoap)(this)).Quiter(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Discussion.srv.ws_chatSoap.BeginQuiter(Discussion.srv.QuiterRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginQuiter(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginQuiter(string pseudo, System.AsyncCallback callback, object asyncState) {
            Discussion.srv.QuiterRequest inValue = new Discussion.srv.QuiterRequest();
            inValue.Body = new Discussion.srv.QuiterRequestBody();
            inValue.Body.pseudo = pseudo;
            return ((Discussion.srv.ws_chatSoap)(this)).BeginQuiter(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion.srv.QuiterResponse Discussion.srv.ws_chatSoap.EndQuiter(System.IAsyncResult result) {
            return base.Channel.EndQuiter(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndQuiter(System.IAsyncResult result) {
            Discussion.srv.QuiterResponse retVal = ((Discussion.srv.ws_chatSoap)(this)).EndQuiter(result);
        }
        
        private System.IAsyncResult OnBeginQuiter(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string pseudo = ((string)(inValues[0]));
            return this.BeginQuiter(pseudo, callback, asyncState);
        }
        
        private object[] OnEndQuiter(System.IAsyncResult result) {
            this.EndQuiter(result);
            return null;
        }
        
        private void OnQuiterCompleted(object state) {
            if ((this.QuiterCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.QuiterCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void QuiterAsync(string pseudo) {
            this.QuiterAsync(pseudo, null);
        }
        
        public void QuiterAsync(string pseudo, object userState) {
            if ((this.onBeginQuiterDelegate == null)) {
                this.onBeginQuiterDelegate = new BeginOperationDelegate(this.OnBeginQuiter);
            }
            if ((this.onEndQuiterDelegate == null)) {
                this.onEndQuiterDelegate = new EndOperationDelegate(this.OnEndQuiter);
            }
            if ((this.onQuiterCompletedDelegate == null)) {
                this.onQuiterCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnQuiterCompleted);
            }
            base.InvokeAsync(this.onBeginQuiterDelegate, new object[] {
                        pseudo}, this.onEndQuiterDelegate, this.onQuiterCompletedDelegate, userState);
        }
        
        public void ClearAll() {
            base.Channel.ClearAll();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginClearAll(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginClearAll(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndClearAll(System.IAsyncResult result) {
            base.Channel.EndClearAll(result);
        }
        
        private System.IAsyncResult OnBeginClearAll(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginClearAll(callback, asyncState);
        }
        
        private object[] OnEndClearAll(System.IAsyncResult result) {
            this.EndClearAll(result);
            return null;
        }
        
        private void OnClearAllCompleted(object state) {
            if ((this.ClearAllCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ClearAllCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ClearAllAsync() {
            this.ClearAllAsync(null);
        }
        
        public void ClearAllAsync(object userState) {
            if ((this.onBeginClearAllDelegate == null)) {
                this.onBeginClearAllDelegate = new BeginOperationDelegate(this.OnBeginClearAll);
            }
            if ((this.onEndClearAllDelegate == null)) {
                this.onEndClearAllDelegate = new EndOperationDelegate(this.OnEndClearAll);
            }
            if ((this.onClearAllCompletedDelegate == null)) {
                this.onClearAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnClearAllCompleted);
            }
            base.InvokeAsync(this.onBeginClearAllDelegate, null, this.onEndClearAllDelegate, this.onClearAllCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion.srv.SendMessageResponse Discussion.srv.ws_chatSoap.SendMessage(Discussion.srv.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public Discussion.srv.ChatMessage[] SendMessage(string text, string pseudo) {
            Discussion.srv.SendMessageRequest inValue = new Discussion.srv.SendMessageRequest();
            inValue.Body = new Discussion.srv.SendMessageRequestBody();
            inValue.Body.text = text;
            inValue.Body.pseudo = pseudo;
            Discussion.srv.SendMessageResponse retVal = ((Discussion.srv.ws_chatSoap)(this)).SendMessage(inValue);
            return retVal.Body.SendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Discussion.srv.ws_chatSoap.BeginSendMessage(Discussion.srv.SendMessageRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSendMessage(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSendMessage(string text, string pseudo, System.AsyncCallback callback, object asyncState) {
            Discussion.srv.SendMessageRequest inValue = new Discussion.srv.SendMessageRequest();
            inValue.Body = new Discussion.srv.SendMessageRequestBody();
            inValue.Body.text = text;
            inValue.Body.pseudo = pseudo;
            return ((Discussion.srv.ws_chatSoap)(this)).BeginSendMessage(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion.srv.SendMessageResponse Discussion.srv.ws_chatSoap.EndSendMessage(System.IAsyncResult result) {
            return base.Channel.EndSendMessage(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Discussion.srv.ChatMessage[] EndSendMessage(System.IAsyncResult result) {
            Discussion.srv.SendMessageResponse retVal = ((Discussion.srv.ws_chatSoap)(this)).EndSendMessage(result);
            return retVal.Body.SendMessageResult;
        }
        
        private System.IAsyncResult OnBeginSendMessage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string text = ((string)(inValues[0]));
            string pseudo = ((string)(inValues[1]));
            return this.BeginSendMessage(text, pseudo, callback, asyncState);
        }
        
        private object[] OnEndSendMessage(System.IAsyncResult result) {
            Discussion.srv.ChatMessage[] retVal = this.EndSendMessage(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSendMessageCompleted(object state) {
            if ((this.SendMessageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SendMessageCompleted(this, new SendMessageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SendMessageAsync(string text, string pseudo) {
            this.SendMessageAsync(text, pseudo, null);
        }
        
        public void SendMessageAsync(string text, string pseudo, object userState) {
            if ((this.onBeginSendMessageDelegate == null)) {
                this.onBeginSendMessageDelegate = new BeginOperationDelegate(this.OnBeginSendMessage);
            }
            if ((this.onEndSendMessageDelegate == null)) {
                this.onEndSendMessageDelegate = new EndOperationDelegate(this.OnEndSendMessage);
            }
            if ((this.onSendMessageCompletedDelegate == null)) {
                this.onSendMessageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSendMessageCompleted);
            }
            base.InvokeAsync(this.onBeginSendMessageDelegate, new object[] {
                        text,
                        pseudo}, this.onEndSendMessageDelegate, this.onSendMessageCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion.srv.AllMessagesResponse Discussion.srv.ws_chatSoap.AllMessages(Discussion.srv.AllMessagesRequest request) {
            return base.Channel.AllMessages(request);
        }
        
        public Discussion.srv.ChatMessage[] AllMessages() {
            Discussion.srv.AllMessagesRequest inValue = new Discussion.srv.AllMessagesRequest();
            inValue.Body = new Discussion.srv.AllMessagesRequestBody();
            Discussion.srv.AllMessagesResponse retVal = ((Discussion.srv.ws_chatSoap)(this)).AllMessages(inValue);
            return retVal.Body.AllMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Discussion.srv.ws_chatSoap.BeginAllMessages(Discussion.srv.AllMessagesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAllMessages(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAllMessages(System.AsyncCallback callback, object asyncState) {
            Discussion.srv.AllMessagesRequest inValue = new Discussion.srv.AllMessagesRequest();
            inValue.Body = new Discussion.srv.AllMessagesRequestBody();
            return ((Discussion.srv.ws_chatSoap)(this)).BeginAllMessages(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Discussion.srv.AllMessagesResponse Discussion.srv.ws_chatSoap.EndAllMessages(System.IAsyncResult result) {
            return base.Channel.EndAllMessages(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Discussion.srv.ChatMessage[] EndAllMessages(System.IAsyncResult result) {
            Discussion.srv.AllMessagesResponse retVal = ((Discussion.srv.ws_chatSoap)(this)).EndAllMessages(result);
            return retVal.Body.AllMessagesResult;
        }
        
        private System.IAsyncResult OnBeginAllMessages(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginAllMessages(callback, asyncState);
        }
        
        private object[] OnEndAllMessages(System.IAsyncResult result) {
            Discussion.srv.ChatMessage[] retVal = this.EndAllMessages(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAllMessagesCompleted(object state) {
            if ((this.AllMessagesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AllMessagesCompleted(this, new AllMessagesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AllMessagesAsync() {
            this.AllMessagesAsync(null);
        }
        
        public void AllMessagesAsync(object userState) {
            if ((this.onBeginAllMessagesDelegate == null)) {
                this.onBeginAllMessagesDelegate = new BeginOperationDelegate(this.OnBeginAllMessages);
            }
            if ((this.onEndAllMessagesDelegate == null)) {
                this.onEndAllMessagesDelegate = new EndOperationDelegate(this.OnEndAllMessages);
            }
            if ((this.onAllMessagesCompletedDelegate == null)) {
                this.onAllMessagesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAllMessagesCompleted);
            }
            base.InvokeAsync(this.onBeginAllMessagesDelegate, null, this.onEndAllMessagesDelegate, this.onAllMessagesCompletedDelegate, userState);
        }
    }
}
